// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAh0OLQuZNBFdLBmKSzQGYQZNxA_4mgbt4',
    appId: '1:230350008402:web:d02162a26e5b1db63fef8b',
    messagingSenderId: '230350008402',
    projectId: 'gradproject-34e48',
    authDomain: 'gradproject-34e48.firebaseapp.com',
    storageBucket: 'gradproject-34e48.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1WWgw02K3IoAMWLwwPm3VakTjnE8WxzY',
    appId: '1:230350008402:android:f90c23c1b09badbb3fef8b',
    messagingSenderId: '230350008402',
    projectId: 'gradproject-34e48',
    storageBucket: 'gradproject-34e48.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyb5AhfGgGeZ2AwSOh3wrT9nDh6rubTJI',
    appId: '1:230350008402:ios:cd2596fa3a0eac3d3fef8b',
    messagingSenderId: '230350008402',
    projectId: 'gradproject-34e48',
    storageBucket: 'gradproject-34e48.firebasestorage.app',
    iosBundleId: 'com.example.graduationApp',
  );
}
